name: CI Pipeline

on:
  push:
    branches:
      - test-ci
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Tests
        id: run_tests
        run: |
          pytest --junitxml=results.xml

      - name: Assert Tests Passed
        uses: therussiankid92/gat@v1.9
        with:
          assertion: should.be.true
          expected: "true"
          actual: ${{ steps.run_tests.outcome == 'success' }}
